// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"
	"time"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
  id, sender_name, sender_phone_number, message_text, created_at
) VALUES (
  ?, ?, ?, ?, ?
) RETURNING id, sender_name, sender_phone_number, message_text, created_at
`

type CreateMessageParams struct {
	ID                string
	SenderName        string
	SenderPhoneNumber string
	MessageText       string
	CreatedAt         time.Time
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Messages, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ID,
		arg.SenderName,
		arg.SenderPhoneNumber,
		arg.MessageText,
		arg.CreatedAt,
	)
	var i Messages
	err := row.Scan(
		&i.ID,
		&i.SenderName,
		&i.SenderPhoneNumber,
		&i.MessageText,
		&i.CreatedAt,
	)
	return i, err
}

const getMessages = `-- name: GetMessages :many
SELECT id, sender_name, sender_phone_number, message_text, created_at FROM messages
`

func (q *Queries) GetMessages(ctx context.Context) ([]Messages, error) {
	rows, err := q.db.QueryContext(ctx, getMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Messages
	for rows.Next() {
		var i Messages
		if err := rows.Scan(
			&i.ID,
			&i.SenderName,
			&i.SenderPhoneNumber,
			&i.MessageText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNewPhoneNumbers = `-- name: GetNewPhoneNumbers :many
SELECT sender_phone_number FROM messages
`

func (q *Queries) GetNewPhoneNumbers(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getNewPhoneNumbers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var sender_phone_number string
		if err := rows.Scan(&sender_phone_number); err != nil {
			return nil, err
		}
		items = append(items, sender_phone_number)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
