// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Projects struct {
	ID           string
	Name         string
	Description  string
	StudentEmail string
	StudentName  string
	TechStack    string
	Categories   string
	Stars        int64
	RepoUrl      string
	CreatedAt    time.Time
}
