// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
  id, name, description, student_email, student_name, tech_stack, categories, stars, repo_url
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, name, description, student_email, student_name, tech_stack, categories, stars, repo_url, created_at
`

type CreateProjectParams struct {
	ID           string
	Name         string
	Description  string
	StudentEmail string
	StudentName  string
	TechStack    string
	Categories   string
	Stars        int64
	RepoUrl      string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Projects, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.StudentEmail,
		arg.StudentName,
		arg.TechStack,
		arg.Categories,
		arg.Stars,
		arg.RepoUrl,
	)
	var i Projects
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.StudentEmail,
		&i.StudentName,
		&i.TechStack,
		&i.Categories,
		&i.Stars,
		&i.RepoUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, description, student_email, student_name, tech_stack, categories, stars, repo_url, created_at FROM projects WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id string) (Projects, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Projects
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.StudentEmail,
		&i.StudentName,
		&i.TechStack,
		&i.Categories,
		&i.Stars,
		&i.RepoUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectByRepoURL = `-- name: GetProjectByRepoURL :one
SELECT id, name, description, student_email, student_name, tech_stack, categories, stars, repo_url, created_at FROM projects WHERE repo_url = ?
`

func (q *Queries) GetProjectByRepoURL(ctx context.Context, repoUrl string) (Projects, error) {
	row := q.db.QueryRowContext(ctx, getProjectByRepoURL, repoUrl)
	var i Projects
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.StudentEmail,
		&i.StudentName,
		&i.TechStack,
		&i.Categories,
		&i.Stars,
		&i.RepoUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getProjects = `-- name: GetProjects :many
SELECT id, name, description, student_email, student_name, tech_stack, categories, stars, repo_url, created_at FROM projects ORDER BY created_at DESC
`

func (q *Queries) GetProjects(ctx context.Context) ([]Projects, error) {
	rows, err := q.db.QueryContext(ctx, getProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Projects
	for rows.Next() {
		var i Projects
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.StudentEmail,
			&i.StudentName,
			&i.TechStack,
			&i.Categories,
			&i.Stars,
			&i.RepoUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectsByStudent = `-- name: GetProjectsByStudent :many
SELECT id, name, description, student_email, student_name, tech_stack, categories, stars, repo_url, created_at FROM projects WHERE student_email = ? ORDER BY created_at DESC
`

func (q *Queries) GetProjectsByStudent(ctx context.Context, studentEmail string) ([]Projects, error) {
	rows, err := q.db.QueryContext(ctx, getProjectsByStudent, studentEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Projects
	for rows.Next() {
		var i Projects
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.StudentEmail,
			&i.StudentName,
			&i.TechStack,
			&i.Categories,
			&i.Stars,
			&i.RepoUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const starProject = `-- name: StarProject :one
UPDATE projects SET stars = stars + 1 WHERE id = ? RETURNING id, name, description, student_email, student_name, tech_stack, categories, stars, repo_url, created_at
`

func (q *Queries) StarProject(ctx context.Context, id string) (Projects, error) {
	row := q.db.QueryRowContext(ctx, starProject, id)
	var i Projects
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.StudentEmail,
		&i.StudentName,
		&i.TechStack,
		&i.Categories,
		&i.Stars,
		&i.RepoUrl,
		&i.CreatedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = ?, description = ?, student_email = ?, student_name = ?, tech_stack = ?, categories = ?, stars = ?, repo_url = ?
WHERE id = ?
RETURNING id, name, description, student_email, student_name, tech_stack, categories, stars, repo_url, created_at
`

type UpdateProjectParams struct {
	Name         string
	Description  string
	StudentEmail string
	StudentName  string
	TechStack    string
	Categories   string
	Stars        int64
	RepoUrl      string
	ID           string
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Projects, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.StudentEmail,
		arg.StudentName,
		arg.TechStack,
		arg.Categories,
		arg.Stars,
		arg.RepoUrl,
		arg.ID,
	)
	var i Projects
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.StudentEmail,
		&i.StudentName,
		&i.TechStack,
		&i.Categories,
		&i.Stars,
		&i.RepoUrl,
		&i.CreatedAt,
	)
	return i, err
}
