// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Messages, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Projects, error)
	DeleteProject(ctx context.Context, id string) error
	GetMessages(ctx context.Context) ([]Messages, error)
	GetNewPhoneNumbers(ctx context.Context) ([]string, error)
	GetProject(ctx context.Context, id string) (Projects, error)
	GetProjectByRepoURL(ctx context.Context, repoUrl string) (Projects, error)
	GetProjects(ctx context.Context) ([]Projects, error)
	GetProjectsByStudent(ctx context.Context, studentEmail string) ([]Projects, error)
	StarProject(ctx context.Context, id string) (Projects, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Projects, error)
}

var _ Querier = (*Queries)(nil)
